<?php

namespace ContainerPAKma2R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UlyiPRT.App\Entity\Component' shared service.
     *
     * @return \App\Entity\Component
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UlyiPRT": it references class "App\\Entity\\Component" but no such service exists.');
    }
}
