<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLl41N21\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLl41N21/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLl41N21.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLl41N21\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLl41N21\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ll41N21',
    'container.build_id' => '163ce285',
    'container.build_time' => 1606072693,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLl41N21');
