<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMAE48EI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMAE48EI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMAE48EI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMAE48EI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMAE48EI\App_KernelDevDebugContainer([
    'container.build_hash' => 'MAE48EI',
    'container.build_id' => '8a3fb770',
    'container.build_time' => 1607515723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMAE48EI');
