<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'component_index' => [[], ['_controller' => 'App\\Controller\\ComponentController::index'], [], [['text', '/component/']], [], []],
    'component_new' => [[], ['_controller' => 'App\\Controller\\ComponentController::new'], [], [['text', '/component/new']], [], []],
    'component_show' => [['id'], ['_controller' => 'App\\Controller\\ComponentController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/component']], [], []],
    'component_edit' => [['id'], ['_controller' => 'App\\Controller\\ComponentController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/component']], [], []],
    'component_delete' => [['id'], ['_controller' => 'App\\Controller\\ComponentController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/component']], [], []],
    'find_component_by_name' => [['name'], ['_controller' => 'App\\Controller\\ComponentController::findAllByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/component/find']], [], []],
    'product_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product/']], [], []],
    'product_new' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product/new']], [], []],
    'find_product_by_name' => [['name'], ['_controller' => 'App\\Controller\\ProductController::findAllByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/product/find']], [], []],
    'product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'api_logger_log' => [['name'], ['_controller' => 'App\\Controller\\LogController::logger'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/logger']], [], []],
];
