<?php

namespace ContainerMAE48EI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UlyiPRTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UlyiPRT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UlyiPRT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'component' => ['privates', '.errored..service_locator.UlyiPRT.App\\Entity\\Component', NULL, 'Cannot autowire service ".service_locator.UlyiPRT": it references class "App\\Entity\\Component" but no such service exists.'],
        ], [
            'component' => 'App\\Entity\\Component',
        ]);
    }
}
