<?php

namespace ContainerMAE48EI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QWov0yrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QWov0yr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QWov0yr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'componentRepository' => ['privates', 'App\\Repository\\ComponentRepository', 'getComponentRepositoryService', true],
        ], [
            'componentRepository' => 'App\\Repository\\ComponentRepository',
        ]);
    }
}
